package com.newcat.checkin.dto;

/**
 * Response DTO for check-in operations. Includes the generated feedback_text field.
 * See TDD Section 2.4.1 for the full response contract.
 */

import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

@Data
@NoArgsConstructor
public class CheckinResponse {

    private UUID id;
    private UUID petId;
    private LocalDate date;
    private String eatingLevel;
    private String eatingNotes;
    private String litterStatus;
    private String litterNotes;
    private String activityLevel;
    private String activityNotes;
    private String ownerNotes;
    private Integer confidenceScore;

    // Generated by FeedbackService — TDD Section 2.4.1
    private String feedbackText;

    private LocalDateTime createdAt;
}
